name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.12
    
    - name: Install dependencies
      run: uv sync --group dev
    
    - name: Run tests
      env:
        ANTHROPIC_API_KEY: test-key-for-ci
      run: |
        uv run pytest tests/ -v
    
    - name: Build package
      run: uv build
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*
        body: |
          Release ${{ github.ref_name }}
          
          ## Changes
          See [CHANGELOG.md](CHANGELOG.md) for details.
          
          ## Installation
          ```bash
          pip install analytics-assistant==${{ github.ref_name }}
          ```
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}